node("slave-docker") {
    docker.withRegistry('https://hub.docker.com/u/inforedaster/', '621e99e4-32cb-4f57-9466-3572d4e4e879') {
    
        git url: "https://github.com/inforedaster/docker-jenkins-zabbix.git"
    
        sh "git rev-parse HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
        println commit_id
    
        stage "build"
        def app = docker.build "inforedaster/jenkins-slave"
    
        stage "publish"
        app.push 'master'
        app.push "${commit_id}"
    }
}
